### ISSUE TITLE
Crash in Session.close() on 1.2.0 – AttributeError: 'NoneType' object has no attribute 'in_use'

### ISSUE THREAD

**Issue by adamrothman** [neo4j/neo4j-python-driver#144]
This is a crash that's occurring when I try to run a statement using a session, like so:

```python
from neo4j.v1 import basic_auth
from neo4j.v1 import GraphDatabase

driver = GraphDatabase.driver(f'{protocol}://{host}:{port}', auth=basic_auth('neo4j', 'password'))
with driver.session() as session:
    result = session.run('MATCH (a:Actor) RETURN a')
return result
```

With the following stack trace:

```
/usr/local/lib/python3.6/site-packages/neo4j/v1/api.py in __exit__(self, exc_type, exc_value, traceback)
    227 
    228     def __exit__(self, exc_type, exc_value, traceback):
--> 229         self.close()
    230 
    231     def _connect(self, access_mode=None):

/usr/local/lib/python3.6/site-packages/neo4j/v1/api.py in close(self)
    259         finally:
    260             self._closed = True
--> 261         self._disconnect(sync=True)
    262 
    263     def closed(self):

/usr/local/lib/python3.6/site-packages/neo4j/v1/api.py in _disconnect(self, sync)
    243             if sync:
    244                 self._connection.sync()
--> 245             self._connection.in_use = False
    246             self._connection = None
    247             self._connection_access_mode = None

AttributeError: 'NoneType' object has no attribute 'in_use'
```

Using Python 3.6 and neo4j-driver 1.2.0.

**Comment by adamrothman** [comment]
@technige It looks like this was introduced in 1.2.0 as the exact same thing works with 1.1.0.

**Comment by technige** [comment]
Looks like a bug. I'll investigate.

**Comment by crooksecurity** [comment]
Running into the same thing.
Stack Trace:
```
Traceback (most recent call last):
  File "euryale.py", line 49, in <module>
    session.close()
  File "/usr/local/lib/python2.7/dist-packages/neo4j/v1/api.py", line 261, in close
    self._disconnect(sync=True)
  File "/usr/local/lib/python2.7/dist-packages/neo4j/v1/api.py", line 245, in _disconnect
    self._connection.in_use = False
AttributeError: 'NoneType' object has no attribute 'in_use'
```

Code:
```
    if result_context.has_results:
        search_result = result_context.get_results(limit=10)
        print "Results:"
        for item in search_result["items"]:
            print "    %s: %s" %(item["output"]['HostInfo|hostname'], item["output"]['HostInfo|ip_address'])
            session.run("MERGE (computer:Computer {Name: \"%s\"}) SET computer.ipaddress = \"%s\"" \
                % (item["output"]['HostInfo|hostname'], item["output"]['HostInfo|ip_address']))
    session.close()
```

**Comment by yoovraj** [comment]
Hello 
I am also getting similar error

` 
Traceback (most recent call last):
  File "updateNeo4j.py", line 75, in <module>
    session.close()
  File "/usr/lib/python3.5/site-packages/neo4j/v1/api.py", line 261, in close
    self._disconnect(sync=True)
  File "/usr/lib/python3.5/site-packages/neo4j/v1/api.py", line 245, in _disconnect
    self._connection.in_use = False
AttributeError: 'NoneType' object has no attribute 'in_use'
`
Environment 
python3.5, pip3.5
CentOS release 6.8 (Final)

**Comment by B-Stefan** [comment]
Are you sure that this bug is resolved? 
I still get this error when I try to close a session (neo4-driver: 1.2.1) : 

```   
with self.driver.session() as session:
            for project in projects:
                print(project)
                session.run("MERGE (p:Project {name: {project}})",project._asdict())

```

```
  File "/env/lib/python3.5/site-packages/dlr_topic_network-0.3-py3.5.egg/dlrtopicimporter/neo4j.py", line 61, in save_projects
    session.run("MERGE (p:Project {name: {project}})",project._asdict())
  File "/env/lib/python3.5/site-packages/neo4j_driver-1.2.1-py3.5-macosx-10.11-x86_64.egg/neo4j/v1/api.py", line 229, in __exit__
    self.close()
  File "/env/lib/python3.5/site-packages/neo4j_driver-1.2.1-py3.5-macosx-10.11-x86_64.egg/neo4j/v1/api.py", line 261, in close
    self._disconnect(sync=True)
  File "/env/lib/python3.5/site-packages/neo4j_driver-1.2.1-py3.5-macosx-10.11-x86_64.egg/neo4j/v1/api.py", line 245, in _disconnect
    self._connection.in_use = False
AttributeError: 'NoneType' object has no attribute 'in_use'

```

**Comment by technige** [comment]
The fix has not yet been released. Expect it in the next patch.
